// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: moderation.proto

package moderation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MuteStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteStatusRequest) Reset() {
	*x = MuteStatusRequest{}
	mi := &file_moderation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteStatusRequest) ProtoMessage() {}

func (x *MuteStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteStatusRequest.ProtoReflect.Descriptor instead.
func (*MuteStatusRequest) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{0}
}

func (x *MuteStatusRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MuteStatusRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MuteStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMuted       bool                   `protobuf:"varint,1,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteStatusResponse) Reset() {
	*x = MuteStatusResponse{}
	mi := &file_moderation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteStatusResponse) ProtoMessage() {}

func (x *MuteStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteStatusResponse.ProtoReflect.Descriptor instead.
func (*MuteStatusResponse) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{1}
}

func (x *MuteStatusResponse) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *MuteStatusResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_moderation_proto protoreflect.FileDescriptor

const file_moderation_proto_rawDesc = "" +
	"\n" +
	"\x10moderation.proto\x12\n" +
	"moderation\"E\n" +
	"\x11MuteStatusRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"G\n" +
	"\x12MuteStatusResponse\x12\x19\n" +
	"\bis_muted\x18\x01 \x01(\bR\aisMuted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2a\n" +
	"\x11ModerationService\x12L\n" +
	"\vIsUserMuted\x12\x1d.moderation.MuteStatusRequest\x1a\x1e.moderation.MuteStatusResponseBAZ?go-stream/services/main-api/internal/grpc/moderation;moderationb\x06proto3"

var (
	file_moderation_proto_rawDescOnce sync.Once
	file_moderation_proto_rawDescData []byte
)

func file_moderation_proto_rawDescGZIP() []byte {
	file_moderation_proto_rawDescOnce.Do(func() {
		file_moderation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moderation_proto_rawDesc), len(file_moderation_proto_rawDesc)))
	})
	return file_moderation_proto_rawDescData
}

var file_moderation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moderation_proto_goTypes = []any{
	(*MuteStatusRequest)(nil),  // 0: moderation.MuteStatusRequest
	(*MuteStatusResponse)(nil), // 1: moderation.MuteStatusResponse
}
var file_moderation_proto_depIdxs = []int32{
	0, // 0: moderation.ModerationService.IsUserMuted:input_type -> moderation.MuteStatusRequest
	1, // 1: moderation.ModerationService.IsUserMuted:output_type -> moderation.MuteStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moderation_proto_init() }
func file_moderation_proto_init() {
	if File_moderation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moderation_proto_rawDesc), len(file_moderation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderation_proto_goTypes,
		DependencyIndexes: file_moderation_proto_depIdxs,
		MessageInfos:      file_moderation_proto_msgTypes,
	}.Build()
	File_moderation_proto = out.File
	file_moderation_proto_goTypes = nil
	file_moderation_proto_depIdxs = nil
}
